# Generated by Django 4.1.5 on 2023-10-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=100)),
                ('redeemed', models.CharField(max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Front.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Front.customers')),
            ],
        ),
    ]
