# Generated by Django 4.1.5 on 2023-11-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_alter_payments_amount_alter_points_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='full_name',
        ),
    ]
