# Generated by Django 4.1.5 on 2023-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_rename_name_customers_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='phone',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='added_on',
            new_name='changed_on',
        ),
        migrations.AddField(
            model_name='customers',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='redeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
